name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "25"
          distribution: graalvm
          cache: maven
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests with Maven Wrapper
        run: ./mvnw --batch-mode verify
